---
- name: OSSec rules file transfer
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    backup: 'yes'
    owner: 'ossec'
    group: 'ossec'
    mode: '0640'
  loop: '{{ ossec_rules }}'
  notify: Enable OSSec service.

- name: OSSec decoders file transfer
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    backup: 'yes'
    owner: 'ossec'
    group: 'ossec'
    mode: '0640'
  loop: '{{ ossec_decoders }}'
  notify: Enable OSSec service.

- name: OSSec shared agent configuration file transfer
  template:
    src: 'agent.conf.j2'
    dest: '/var/ossec/etc/shared/default/agent.conf'
    backup: 'yes'
    owner: 'ossec'
    group: 'ossec'
    mode: '0660'
    validate: '/var/ossec/bin/verify-agent-conf -f %s'
  notify: Enable OSSec service.

- name: OSSec api configuration file transfer
  template:
    src: 'config.js.j2'
    dest: '/var/ossec/api/configuration/config.js'
    backup: 'yes'
    owner: 'root'
    group: 'ossec'
    mode: '0740'
  notify: Enable OSSec service.

- name: OSSec internal options configuration file transfer
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    backup: 'yes'
    owner: 'root'
    group: 'ossec'
    mode: '0640'
  loop: '{{ ossec_internal_options }}'
  notify: Enable OSSec service.

- name: Enable OSSec syslog
  command: '/var/ossec/bin/ossec-control enable client-syslog'
  when:
    - ossec_manager_config.syslog_outputs is defined
    - ossec_manager_config.syslog_outputs[0].server is not none
  notify: Enable OSSec service.

- name: Enable OSSec agentlessd
  command: '/var/ossec/bin/ossec-control enable agentless'
  when: ossec_agentless_creds is defined
  notify: Enable OSSec service.

- name: OSSec agent authentication file transfer
  template:
    src: 'authd.pass.j2'
    dest: '/var/ossec/etc/authd.pass'
    backup: 'yes'
    owner: 'ossec'
    group: 'ossec'
    mode: '0640'
  no_log: true

- name: Configure OSSec API authentication
  htpasswd:
    path: '/var/ossec/api/configuration/auth/user'
    name: '{{ item }}'
    password: '{{ ossec_api_pass }}'
    owner: 'root'
    group: 'root'
    mode: '0660'
  loop:
    - 'foo'
    - 'wazuh'
  no_log: true
  when: ossec_version.split(".")[0] == "3"

- name: OSSec server configuration file transfer
  template:
    src: 'server.conf.j2'
    dest: '/var/ossec/etc/ossec.conf'
    backup: 'yes'
    owner: 'root'
    group: 'ossec'
    mode: '0640'
  notify: Enable OSSec service.

- name: Starting OSSec manager service delayed
  lineinfile:
    state: 'present'
    dest: '/lib/systemd/system/wazuh-manager.service'
    insertafter: '^\[Service\]'
    regexp: '^ExecStartPre'
    line: 'ExecStartPre=-/bin/sleep 60'

- name: Logs Lifecycle Management
  cron:
    user: 'root'
    name: 'OSSec maintenance task'
    minute: "{{ 59 | random(seed=ansible_hostname) }}"
    hour: "{{ (( ansible_hostname | hash | list | map('int',0,16) | sum ) % 2) + 1 }}"
    job: '/bin/find /var/ossec/logs -mtime +{{ ossec_manager_config.archive_rotate_day }} -name "*.gz" -exec /bin/rm -rf {} \; >/dev/null 2>&1'