---
- name: OSSec rules file transfer
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    backup: 'yes'
    owner: 'ossec'
    group: 'ossec'
    mode: '0640'
  loop: '{{ ossec_rules }}'
  register: local_rules_update

- name: OSSec decoders file transfer
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    backup: 'yes'
    owner: 'ossec'
    group: 'ossec'
    mode: '0640'
  loop: '{{ ossec_decoders }}'
  register: local_decoders_update

- name: OSSec shared agent configuration file transfer
  template:
    src: 'agent.conf.j2'
    dest: '/var/ossec/etc/shared/default/agent.conf'
    backup: 'yes'
    owner: 'ossec'
    group: 'ossec'
    mode: '0660'
    validate: '/var/ossec/bin/verify-agent-conf -f %s'
  register: agent_conf_udpate

- name: OSSec api configuration file transfer
  template:
    src: 'config.js.j2'
    dest: '/var/ossec/api/configuration/config.js'
    backup: 'yes'
    owner: 'root'
    group: 'ossec'
    mode: '0740'
  register: api_conf_update

- name: OSSec internal options configuration file transfer
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    backup: 'yes'
    owner: 'root'
    group: 'ossec'
    mode: '0640'
  loop: '{{ ossec_internal_options }}'
  register: internal_conf_update

- name: Enable OSSec syslog
  command: '/var/ossec/bin/ossec-control enable client-syslog'
  when:
    - ossec_manager_config.syslog_outputs is defined
    - ossec_manager_config.syslog_outputs[0].server is not none
  register: syslog_conf_update

- name: Enable OSSec agentlessd
  command: '/var/ossec/bin/ossec-control enable agentless'
  when: ossec_agentless_creds is defined
  register: agentless_conf_update

- name: OSSec agent authentication file transfer
  template:
    src: 'authd.pass.j2'
    dest: '/var/ossec/etc/authd.pass'
    backup: 'yes'
    owner: 'ossec'
    group: 'ossec'
    mode: '0640'
  no_log: true

- name: OSSec API authentication file transfer
  template:
    src: 'user.j2'
    dest: "/var/ossec/api/configuration/auth/user"
    backup: 'yes'
    owner: 'root'
    group: 'root'
    mode: '0660'
  no_log: true

- name: OSSec server configuration file transfer
  template:
    src: 'server.conf.j2'
    dest: '/var/ossec/etc/ossec.conf'
    backup: 'yes'
    owner: 'root'
    group: 'ossec'
    mode: '0640'
  register: server_conf_udpate

- name: Starting OSSec manager service delayed
  lineinfile:
    state: 'present'
    dest: '/etc/systemd/system/wazuh-manager.service'
    insertafter: '^\[Service\]'
    regexp: '^ExecStartPre'
    line: 'ExecStartPre=-/bin/sleep 60'

- name: Logs Lifecycle Management
  cron:
    user: 'root'
    name: 'OSSec maintenance task'
    minute: "{{ 59 | random(seed=inventory_hostname) }}"
    hour: "{{ (( ansible_hostname | hash | list | map('int',0,16) | sum ) % 2) + 1 }}"
    job: '/bin/find /var/ossec/logs -mtime +{{ ossec_rotate_day }} -name "*.gz" -exec /bin/rm -rf {} \; >/dev/null 2>&1'
