---
- name: Ossec exporter program binary transfer.
  unarchive:
    src: 'ossec-metrics.tar.xz'
    dest: '/usr/local/bin'
    owner: 'root'
    group: 'root'
    mode: '0750'
  notify: Reloading the Ossec exporter service.

- name: Ossec service file transfer.
  copy:
    src: 'ossec_exporter.service'
    dest: '/lib/systemd/system/ossec_exporter.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: Reloading the Ossec exporter service.