---
- name: Creating vulnerability feeds offline update folder.
  file:
    dest: '/var/ossec/var/feed'
    state: 'directory'
    owner: 'ossec'
    group: 'root'
    mode: '770'

- name: RedHat CVE data download script transfer.
  copy:
    src: 'rh-generator.sh'
    dest: '/var/ossec/bin'
    owner: 'ossec'
    group: 'root'
    mode: '750'
  when: '"redhat" in ossec_manager_config.vul_detector.provider'

- name: Create a scheduled task to downloading OVAL feed.
  cron:
    user: 'ossec'
    name: 'Offline update by {{ item.feed }}'
    special_time: 'daily'
    job: '/bin/wget -P /var/ossec/var/feed {{ item.feed }}'
  loop: '{{ ossec_oval_feed }}'
  when: item.create | default(true) | bool

- name: Create a scheduled task to downloading RedHat CVE data.
  cron:
    user: 'ossec'
    name: 'Offline update by RedHat CVE'
    special_time: 'daily'
    job: '/bin/bash /var/ossec/bin/rh-generator.sh /var/ossec/var/feed'
  when: '"redhat" in ossec_manager_config.vul_detector.provider'
