---
- name: Create an index lifecycle policy.
  uri:
    url: '{% if ossec_elastic_stack_auth | bool and ossec_elastic_stack_https | bool %}https{% else %}http{% endif %}://{{ ossec_servers[0] }}:{{ ossec_elastic_port | default("9200") }}/_ilm/policy/ilm-history-{{ ossec_manager_config.elastic_rotate_day | default("180") }}d-policy'
    method: 'PUT'
    user: '{{ ossec_elastic_stack_user }}'
    password: '{{ ossec_elastic_stack_pass }}'
    validate_certs: 'no'
    body: '{"policy":{"phases":{"hot":{"min_age":"0ms","actions":{"set_priority":{"priority":100}}},"delete":{"min_age":"180d","actions":{"delete":{}}}}}}'
    body_format: 'json'
    force_basic_auth: 'yes'
  environment:
    no_proxy: '{{ ossec_servers[0] }}'
  register: ossec_ilm_status
  until: ossec_ilm_status.status == 200
  retries: 5
  delay: 2
  changed_when: false
  failed_when: false
  no_log: true
