---
- name: Sets ElasticSearch node variables for Cluster.
  set_fact:
    ossec_elastic_hosts: '{{ ossec_servers }}'
  when:
    - ossec_elastic_stack_dept | bool

#- name: Set machine timezone
#  timezone:
#    name: 'UTC'

# OSSEC chroots most of its processes to the install directory and will not be able to move, So be sure to allocate enough space to /var/ossec.
#- name: Creating OSSec data folder
#  file:
#    dest: '{{ ossec_path }}/ossec'
#    state: 'directory'

#- name: Mount and bind OSSec data volume
#  mount:
#    src: '{{ ossec_path }}/ossec'
#    path: '/var/ossec'
#    opts: 'bind'
#    state: 'mounted'
#    fstype: 'none'

#- name: Change OSSec data folder ownership
#  file:
#    path: '{{ ossec_path }}/ossec'
#    owner: 'root'
#    group: 'ossec'
#    mode: '0750'

- name: Include tasks for specific OS.
  include: '{{ ansible_os_family }}.yml'

- name: Straight to getenforce selinux status.
  include: 'selinux.yml'

- name: Include firewall tasks.
  include: 'firewall.yml'

- name: Configuration the OSSec manager.
  include: 'configureation.yml'

- name: Configuration the OSQuery.
  include: 'osquery.yml'
  when: ossec_manager_config.osquery.disable == 'no'

- name: Reload the OSSec service.
  shell: echo ''
  notify: 'Ensure OSSec service is enabled'
  when: local_rules_update is changed or local_decoders_update is changed or agent_conf_udpate is changed or api_conf_update is changed or internal_conf_update is changed or syslog_conf_update is changed or agentless_conf_update is changed or server_conf_udpate is changed

- name: Force the handler to run immediately
  meta: flush_handlers

- name: Ensure MTA service is enabled.
  systemd:
    name: 'postfix.service'
    enabled: 'yes'
    state: 'started'
  when: ossec_mail_arg.email_notification == 'yes'

#- name: Remove OSSec metadata
#  include: 'cleanup.yml'

#- name: Curator tasks
#  include: 'curator.yml'
#  when: ossec_servers[0] in ansible_default_ipv4.address

- name: Include Index Lifecycle Policies tasks.
  include: 'ilm.yml'
  when: ossec_servers[0] in ansible_default_ipv4.address

- name: Create Wazuh APP plugins bundles directory.
  file:
    path: '/usr/share/kibana/optimize/wazuh/config'
    state: 'directory'
    owner: 'kibana'
    group: 'kibana'
    mode: '0755'

- name: Wazuh APP plugins Configuration.
  template:
    src: 'wazuhapp_config.yml'
    dest: '/usr/share/kibana/optimize/wazuh/config/wazuh.yml'
    owner: 'kibana'
    group: 'kibana'
    mode: '0644'
  changed_when: false
  failed_when: false

- name: Include API tasks.
  include: 'api.yml'
  when: ossec_version.split(".")[0] != "3"

- name: Include prometheus exporter tasks.
  include: 'exporter.yml'
  when: exporter_is_install | bool

- name: Registered with HashiCorp Consul.
  include: 'register.yml'
  when:
    - exporter_is_install | bool
    - consul_public_register | bool

- name: Include feed tasks.
  include: 'feeds.yml'
  when: ossec_servers[0] in ansible_default_ipv4.address
