---
- name: Include OS-specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: 'Add EPEL YUM repositories'
  yum_repository:
    name: '{{ epel_repo_name }}'
    description: '{{ epel_repo_name }} YUM repo'
    file: '{{ epel_repo_name }}'
    baseurl: '{{ epel_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: 'Add OSQuery YUM repositories'
  yum_repository:
    name: '{{ osquery_repo_name }}'
    description: '{{ osquery_repo_name }} YUM repo'
    file: '{{ osquery_repo_name }}'
    baseurl: '{{ osquery_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: 'Add OSSec YUM repositories'
  yum_repository:
    name: '{{ ossec_repo_name }}'
    description: '{{ ossec_repo_name }} YUM repo'
    file: '{{ ossec_repo_name }}'
    baseurl: '{{ ossec_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: Install the OSSec dependents packages
  yum:
    name: '{{ ossec_dependent_packages }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: yum_status
  until: yum_status is succeeded
  retries: 5
  delay: 2

- name: Install the OSSec packages
  yum:
    name: '{{ ossec_packages }}'
    state: 'present'
    enablerepo: '{{ ossec_repo_name }}'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: yum_status
  until: yum_status is succeeded
  retries: 5
  delay: 2
