---
- name: Include OS-specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: 'Add EPEL YUM repositories'
  yum_repository:
    name: '{{ epel_repo_name }}'
    description: '{{ epel_repo_name }} YUM repo'
    file: '{{ epel_repo_name }}'
    baseurl: '{{ epel_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: 'Add OSSEC YUM repositories'
  yum_repository:
    name: '{{ ossec_repo_name }}'
    description: '{{ ossec_repo_name }} YUM repo'
    file: '{{ ossec_repo_name }}'
    baseurl: '{{ ossec_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: Install the OSSEC dependents packages
  yum:
    name: '{{ item }}'
    state: 'present'
    enablerepo: '{{ epel_repo_name }}'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  loop: '{{ ossec_dependent_packages }}'

- name: Install the OSSEC packages
  yum:
    name: '{{ item }}'
    state: 'present'
    enablerepo: '{{ ossec_repo_name }}'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  loop: '{{ ossec_packages }}'
