---
- name: 'Set ossec_selinux to false for default'
  set_fact:
    ossec_selinux: '{{ false }}'

- name: 'Get getenforce binary'
  stat:
    path: '/usr/sbin/getenforce'
  register: getenforce_bin
  become: yes

- name: 'Collect getenforce output'
  command: getenforce
  register: sestatus
  when: 'getenforce_bin.stat.exists'
  changed_when: false
  become: yes

- name: 'Set ossec_selinux to true if getenforce returns Enforcing or Permissive'
  set_fact:
    ossec_selinux: '{{ true }}'
  when: 'getenforce_bin.stat.exists and ("Enforcing" in sestatus.stdout or "Permissive" in sestatus.stdout)'

- name: Allow OSSec to listen on service port
  seport:
    ports: '{{ item[1] }}'
    proto: '{{ item[2] }}'
    setype: 'http_port_t'
    state: 'present'
  with_nested:
    - '{{ ossec_port_arg | dictsort }}'
    - [ 'tcp', 'udp' ]
  when: ossec_selinux | bool
