---
- name: Enable OSSec service
  systemd:
    name: '{{ item.package }}.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
  loop: '{{ ossec_packages }}'
  when: item.create | default(true) | bool
  listen: Ensure OSSec service is enabled
