---
- name: Enable OSSec service
  systemd:
    name: '{{ item }}'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
  loop:
    - 'wazuh-api.service'
    - 'wazuh-manager.service'
  listen: Ensure OSSec service is enabled
