---
- name: Enable OSSec service.
  systemd:
    name: '{{ item.package }}.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
  loop: '{{ ossec_packages }}'
  when: item.create | default(true) | bool

- name: Reloading the Ossec exporter service.
  systemd:
    name: 'ossec_exporter.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'