---
wazuh.shards: {{ ossec_server | length }}
wazuh.replicas: {% if ( ossec_server | length - 1 ) >= 2 %}2{% else %}{{ ossec_server | length - 1 }}{% endif %}

wazuh-version.shards: {{ ossec_server | length }}
wazuh-version.replicas: {% if ( ossec_server | length - 1 ) >= 2 %}2{% else %}{{ ossec_server | length - 1 }}{% endif %}
